name: Main Build
on:  
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]        
    workflow_dispatch:

concurrency: 
  group: release-${{github.repository}}
  cancel-in-progress: true

env:
  JF_URL: "https://sirahurajesh.jfrog.io/artifactory/libs-snapshot-local/"
  JFROG_ARTIFACTORY_REPONAME: "libs-snapshot-local"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2     
      
      - uses: actions/cache@v1
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
                ${{ runner.os }}-maven-
                
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          overwrite-settings: false
          
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
            repositories: >
              [           
                {
                  "id": "Artifactory",
                  "name": "Mule Public Repository",
                  "url": "${env.JF_URL}",
                  "releases": {
                    "enabled": "true"
                  },
                  "snapshots": {
                    "enabled": "true"
                  }
                }           
              ]
            plugin_repositories: >
              [
                {
                  "id": "Artifactory",
                  "name": "Mule Public Repository",
                  "url": "${env.JF_URL}",
                  "releases": {
                    "enabled": "true"
                  },
                  "snapshots": {
                    "enabled": "true"
                  }
                }
              ]
            servers: >
              [                           
                {
                  "id": "Artifactory",
                  "username": "${{ secrets.JF_USER }}",
                  "password": "${{ secrets.JF_PASSWORD }}"
                }
              ]   
      - name: Setup JFrog CLI
        # Install CLI 
        uses: jfrog/setup-jfrog-cli@v3
        env:
            # JFrog platform url (for example: https://acme.jfrog.io) 
            JF_URL: ${{ secrets.JF_URL }}

            # Basic authentication credentials
            JF_USER: ${{ secrets.JF_USER }}
            JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
            # JFrog Platform access token
            JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
       
    # JFrog Ping 
      - name: Ping JFrog CLI 
        run: |         
           jf rt ping
      - name: Build the Project
        run: mvn clean install -DskipTests
          
      # Deploy to Maven Central
      - name: Deploy to Maven Central
        run: mvn -B deploy
