name: Reusable workflow example

on: 
  workflow_dispatch:
  
  jobs:
  do-it:
   runs-on: ubuntu-latest
   
   steps:
    -uses: actions/checkout@v2
    
    -name: Run a one-line script
    run: echo Hello, World!
    
 docker:
  jobs:
  call-workflow-1-in-local-repo:
    uses: octo-org/this-repo/.github/workflows/workflow-1.yml@172239021f7ba04fe7327647b213799853a9eb89
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/workflow-2.yml
  call-workflow-in-another-repo:
    uses: octo-org/another-repo/.github/workflows/workflow.yml@v1
  with:
  image-name: my_awesome-app
  tag: $GITHUB_RUN_NUMBER
  secrets:
  registry_username: ${{secrets>REGISTRY_USERNAME}}
  registry_password: ${{secrets>REGISTRY_PASSWORD}}
